name: Generate plots

on:
  push:
    tags:
      - v*.*.*

jobs:
  plot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: |
          python -m pip install --upgrade pip
          pip install matplotlib pandas requests
      - run: |
          cd scripts/
          python -m fig.main
      - run: ls -la scripts/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: scripts/*.pdf
